### PR TITLE
I've made this fix so I can pass the setup wizard

### PR DESCRIPTION
**Pull request by eboye**

### CODE REVIEW

**Comment by mohitpanjwani** [comment]
I think this change would make the app prone to some weird timezone or file disk-related issues. 

Also, the reason why you got the error was that we put the `database_created` file when the new version was launched in the zip file by mistake. 

But it shouldn't be an issue anymore for users who downloaded the zip file the next day onwards 🤔

**Comment by eboye** [comment]
OK, not sure how it would cause the issues, but I don't know how the whole app is structured, so you have the best overview on this. If it works, it works :D That's the end goal ;)

**Comment by mohitpanjwani** [comment]
Cool :) 

Thank you for taking the time to create a PR though 👍

**Comment by eboye** [comment]
No prob ;) I was just trying to help :)

**Pull request closed without merging**
