### PR TITLE
Adding dutch translations

### PR DESCRIPTION
**Pull request by ryanlupescu**

### CODE REVIEW

**Comment by miraro3** [comment]
Yay, a Dutch translation! This is far from complete though.

I'm quite new to the whole open source idea. Do pull requests get accepted when the code commited is only partially done?

**Comment by mohitpanjwani** [comment]
Hi @miraro3, no we wouldn't accept a partial PR but Are you familiar with dutch? 

There's one other PR for dutch translation which looks complete but I'm not sure which one's better as I can't read Dutch :) 

Can you help us review and check which one's complete? 
https://github.com/bytefury/crater/pull/144

Thanks 👍

**Comment by ryanlupescu** [comment]
I thought i'd start to translate the dutch strings, but I haven't enough time to complete it so i'd push so anyone else also can contribute it.

**Comment by mohitpanjwani** [comment]
Thanks for your contribution @ryanlupescu 👍

**Comment by mohitpanjwani** [comment]
I'll close this as there's already another PR which is almost complete for dutch language.

**Pull request closed without merging**
