### PR TITLE
Serbian lang

### PR DESCRIPTION
**Pull request by azaricstefan**

### CODE REVIEW

**Comment by mohitpanjwani** [comment]
@azaricstefan Hey! Thanks for the PR :) 

Btw can you run `yarn production` instead of `yarn run dev` so it generates versioned & minified public files.

**Comment by azaricstefan** [comment]
Sure, just updated the PR. 😄 
Btw, I had some issue that translation didn't worked until I removed - form the name of the JSON file, could be that something was cached on my machine, that's the reason why I renamed to just sr.json.

**Comment by mohitpanjwani** [comment]
@azaricstefan thanks! I tested this MR but the language didn't appear because you will still need to update the `config.crater.php` to following: 
```
["code"=>"sr", "name" => "Serbian Latin"],
```

The above code should be `sr` instead of `sr_LA` now.

**Comment by mohitpanjwani** [comment]
Other than this, it looks goood to go 👍

**Comment by azaricstefan** [comment]
Ah, forgot to commit it. Just pushed that change. 👍

**Comment by azaricstefan** [comment]
You merged before I did the push btw, please merge this PR #314

**Pull request merged**
