### PR TITLE
feat: Added MAD (Moroccan dirham) currency

### PR DESCRIPTION
**Pull request by MouadZIANI**

### CODE REVIEW

**Comment by mohitpanjwani** [comment]
Hi @MouadZIANI, can you fix this conflict when you get time? 

I'll merge this as soon as that's done.

**Comment by MouadZIANI** [comment]
It's fixed

**Comment by mohitpanjwani** [comment]
Hey @MouadZIANI , Sorry but this overwrites the `Peruvian Soles` currency. 

You need to keep both of them :)

**Comment by MouadZIANI** [comment]
Check it now

**Pull request merged**
