### PR TITLE
Update french language

### PR DESCRIPTION
**Pull request by RobinDev**

### CODE REVIEW

**Comment by RobinDev** [comment]
Don't merge it, i will make a complete pull request in a few days.

Thank you for your tools, I'm playing with and it's perfect.

**Comment by mohitpanjwani** [comment]
Hey @RobinDev... please let me know when this PR is ready for review.

Thanks

**Comment by RobinDev** [comment]
Just update the PR. It's okay :)

Thank you.

**Comment by mohitpanjwani** [comment]
> Just update the PR. It's okay :)
> 
> Thank you.

Great thanks! 

We're reviewing the changes now.

**Comment by mohitpanjwani** [comment]
```
"general": {    
    "sort_by": "Trier par",
    "ascending": "Ascendante",
    "descending": "Descendante",
    "subject": "matière",
    "message": "Message",
}
"estimates": {
    "no_matching_estimates": "Il n'y a pas d'estimation correspondante!",
    "user_email_does_not_exist": "L'e-mail de l'utilisateur n'existe pas",
    "something_went_wrong": "quelque chose a mal tourné",
}
"invoices": {
    "confirm_send_invoice": "Cette facture sera envoyée par email au client",
    "no_matching_invoices": "Il n'y a pas de factures correspondantes!",
    "cloned_successfully": "Facture clonée avec succès",
    "clone_invoice": "Cloner la facture",
    "confirm_clone": "Cette facture sera clonée dans une nouvelle facture",
    "user_email_does_not_exist": "L'e-mail de l'utilisateur n'existe pas",
    "something_went_wrong": "quelque chose a mal tourné",
}
"payments": {
    "confirm_send_payment": "Ce paiement sera envoyé par e-mail au client",
    "send_payment_successfully": "Paiement envoyé avec succès",
    "user_email_does_not_exist": "L'e-mail de l'utilisateur n'existe pas",
    "something_went_wrong": "quelque chose a mal tourné",
}
"expenses": {
    "customer": "Client",
}
"login": {
    "password_reset_successfully": "réinitialisation du mot de passe réussie",  
}
"settings": {
    "menu_title": {
        "customization": "Personnalisation",
    }
}
"wizard": {
    "skip": "sauter",
}
"validation": {
    "email_already_taken": "L'email a déjà été pris en compte.",
}
```

**Comment by RobinDev** [comment]
I added them without checking in the context. 

If something looks weird to me, I will fix it... but I am not doing a lot of invoices during covid.

**Comment by mohitpanjwani** [comment]
Thank you @RobinDev! this looks PR is good to merge now 👍

**Pull request merged**
