### PR TITLE
Backup invoices on Google Drive

### PR DESCRIPTION
**Pull request by reibengu**
Hey, worked on this feature because my accountant prefers getting the invoices for each client from Google Drive.
This is of course extendable with other cloud storage services by adding the service-job in `AVAILABLE_SERVICES` constant inside `BackupInvoice` + front-end tweaks to insert service and folder_id into `invoice_backup_folders` table.

It is required to have a "Google service account key" inside `storage` folder and set `GOOGLE_SERVICE_ACCOUNT_KEY` env equal to that file name.

For more on how to get the service account key and share access with google drive folder:
https://blog.stapps.io/gdrive-backups-with-service-accounts/

### CODE REVIEW

**Comment by mohitpanjwani** [comment]
Thanks for contributing @reibengu but we've already built this on the upcoming update. 

We've added a File-Disk configuration setting which allows saving PDFs and all other files to various drivers like DO Spaces, Dropbox, S3, etc. 

crater-file-disk

**Comment by reibengu** [comment]
> Thanks for contributing @reibengu but we've already built this on the upcoming update.
> 
> We've added a File-Disk configuration setting which allows saving PDFs and all other files to various drivers like DO Spaces, Dropbox, S3, etc.
> 
> crater-file-disk

Glad to hear that. Not sure if it fulfills my needs as I want each customer to have a separate folder.
If you are open to such a change I might consider working on it after file-disk configuration is released.

**Comment by azaricstefan** [comment]
@reibengu this aligns with my requirements too. If you could share that change in a PR for it that would be great.

@mohitpanjwani is this something which is planned for further improvements on backups feature?

**Comment by reibengu** [comment]
> @reibengu this aligns with my requirements too. If you could share that change in a PR for it that would be great.
> 
> @mohitpanjwani is this something which is planned for further improvements on backups feature?

I didn't have a chance to work on this new feature @mohitpanjwani mentioned.
I'm already using the code from this PR to automatically backup invoices for each customer in Google Drive.

**Comment by mohitpanjwani** [comment]
Closing this because it was built before we added file configuration features and it'll need a lot of work in order to make it work.

**Pull request closed without merging**
