### PR TITLE
Czech locale

### PR DESCRIPTION
**Pull request by TheSkrypt**
Czech localization file added

EDIT: Also, could you please recheck the charset / encoding on the project? For some reason, template 2 and 3 on the invoices have a wrong encoding and Czech characters (such as ě, š, č, ř, ž, ť, ď, ...) don't display/render correctly. Interestingly, template 1 renders correctly even though the charset setting and font used are the same.

### CODE REVIEW

**Comment by TheSkrypt** [comment]
@mohitpanjwani Hi, could you please merge my translations? :)

**Comment by mohitpanjwani** [comment]
Hey, @TheSkrypt thanks for contributing but this cannot be merged in yet as it will need some more changes in order for it to work. 

You can check this MR in order to see what changes are needed in order for the language to work. 

Please let me know if there's any confusion

**Comment by TheSkrypt** [comment]
@mohitpanjwani Hi, I've updated the pull request. Are those all the files you needed to change?

Also, any update on the new 4.0.0 version? :)

**Comment by mohitpanjwani** [comment]
Hey @TheSkrypt, as you might already know.. the new update has been released already. 

Do you have time to make the necessary changes to make Czech locale work ? :)

**Comment by mohitpanjwani** [comment]
Closing this because of inactivity but please feel free to reopen or comment in case you have time to fix this :) @TheSkrypt

**Pull request closed without merging**
