### PR TITLE
One-third of the translation into Russian has been done

### PR DESCRIPTION
**Pull request by Istom1n**
=)

### CODE REVIEW

**Comment by mohitpanjwani** [comment]
Thank you very much @Istom1n. Please let me know when the whole file is translated. 

I'll merge it when its done :)

**Comment by Istom1n** [comment]
> Thank you very much @Istom1n. Please let me know when the whole file is translated.
> 
> I'll merge it when its done :)

No problem.

**Comment by mohitpanjwani** [comment]
Hey @Istom1n , are still looking to translate the remaining sections?

**Comment by Istom1n** [comment]
Why not? At the time I was making the pull request, I translated all the sections. There are new sections now, aren't there?

**Comment by mohitpanjwani** [comment]
Yes, there are are a few new sections now. 

I didn't merge this before because I thought its still pending :)

**Comment by mohitpanjwani** [comment]
Also, btw I think it would be great if you could remove your indentation changes from en.json as that's what resulted into merge conflicts. 

Perhaps just copy en.json from the latest master?

**Comment by Istom1n** [comment]
No, I finished the translation a long time ago :)
Yeah, I'll copy it.

**Comment by mohitpanjwani** [comment]
Thanks @Istom1n 👍

**Comment by mohitpanjwani** [comment]
Hi @Istom1n, do you have any extra time this week to finish the translation for this PR? 

We're looking to create a new release so if this gets completed, then we can include the russian language in this release. 

Thanks

**Comment by mohitpanjwani** [comment]
Closing this because of inactivity but please feel free to reopen or comment in case you have time to fix this :) @Istom1n

**Pull request closed without merging**
