### PR TITLE
Send invoices, estimates and payments as attachments

### PR DESCRIPTION
**Pull request by sebastiancretu**
- There is a new option to enable invoices, estimates and payments as attachments in emails under Settings - Customization
- When sending invoices, estimates and payments as attachments the button to view the invoices, estimates and payments from the emails will not be displayed anymore.

### CODE REVIEW

**Comment by mohitpanjwani** [comment]
Splendid work @sebastiancretu 🔥 

It works as expected and the code looks pretty clean too.. Merging this ✅

**Comment by BIIINO** [comment]
Hello,

i have changed all files as noticed but no options showing under customization tab, of course "yarn dev" succesfully done.

What am i missing ?

**Comment by BIIINO** [comment]
Issue fixed and option is showing, but when i generate invoice and use hyperlink and preview directly in web is int current language, but, when its as attachment in email, it is still in english...any ideas why this happen ?

**Comment by sebastiancretu** [comment]
Yeah. I didn't take that into account. I made a fix for that which I will push soon.

**Pull request merged**
